#!/usr/bin/env bash

main() {
  rm -f www/lavagna_bg.wasm www/lavagna.d.ts www/lavagna.js

  cargo build --release --locked --target wasm32-unknown-unknown

  wasm-bindgen --out-name lavagna \
    --out-dir www \
    --target web target/wasm32-unknown-unknown/release/lavagna.wasm
}

main "$@"
