#!/usr/bin/env bash

main() {
  rm -f www/lavagna_bg.wasm www/lavagna.d.ts www/lavagna.js

  # Some compiler flags to optimize the build for file size
  # All this flags, reduce the size of the final .wasm file fro 18MB to 10MB
  export CARGO_PROFILE_RELEASE_LTO=fat
  export CARGO_PROFILE_RELEASE_OPT_LEVEL=s
  export CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1
  export CARGO_PROFILE_RELEASE_PANIC=abort

  cargo build --release --locked --target wasm32-unknown-unknown

  wasm-bindgen --out-name lavagna \
    --out-dir www \
    --target web target/wasm32-unknown-unknown/release/lavagna.wasm
}

main "$@"
