#!/usr/bin/env bash

main() {
  rm -f www/lavagna-*.* www/index.html

  # Some compiler flags to optimize the build for file size
  # All this flags, reduce the size of the final .wasm file fro 18MB to 10MB
  export CARGO_PROFILE_RELEASE_LTO=fat
  export CARGO_PROFILE_RELEASE_OPT_LEVEL=s
  export CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1
  export CARGO_PROFILE_RELEASE_PANIC=abort

  cargo build --release --locked --target wasm32-unknown-unknown

  # Prevent browser caching
  local unique_id=$( printf "%02X" $( date +%s ) )

  wasm-bindgen --out-name lavagna-${unique_id} \
    --out-dir www \
    --target web target/wasm32-unknown-unknown/release/lavagna.wasm

  cp www/index.html.template www/index.html
  sed -i "s/lavagna.*\.js/lavagna-${unique_id}\.js/g" www/index.html

  # If the http server supports it, the gz file will be used Example: busybox
  # httpd sends files using GZIP content encoding if the client supports it and
  # a pre-compressed <file>.gz exists.
  gzip --keep www/lavagna-${unique_id}_bg.wasm
}

main "$@"
